### ISSUE TITLE
[question]How can I search for a custom location config like ncm2_pyclang#args_file_path?

### ISSUE THREAD

**Issue by fcying** [ncm2/ncm2-vim-lsp#4]
`ncm2-pyclang` can set `g:ncm2_pyclang#args_file_path = ['.git/.clang_complete']` to load config in `.git` dir.
I want put `compile_flags.txt` to `.git` too.

**Comment by roxma** [comment]
You should post the qyestion on https://github.com/prabirshrestha/vim-lsp

By the way, you need to elaborate. I guess it's related to ccls or clangd configuration. But I'm not familiar with them.
